version: "3.3"
   
services:
  db:
    container_name: dbpostgres
    image: postgres:latest
    volumes:
      - postgis-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
      
  backend:
    build: ./
    container_name: backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000 -v2"

volumes:
  postgis-data:
