# Generated by Django 4.0.4 on 2022-05-07 20:48

import apps.base.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('enrollment_number', models.AutoField(help_text='Unique number for identify a student', primary_key=True, serialize=False, unique=True, verbose_name='Enrolment number')),
                ('nickname', models.CharField(help_text='Name to display in the interface', max_length=24, verbose_name='Nickname')),
                ('address', models.CharField(help_text='Student Address', max_length=128, verbose_name='Address')),
                ('age', models.CharField(help_text='Student Age', max_length=128, verbose_name='Age')),
                ('doc', models.CharField(max_length=18, unique=True, verbose_name='Identity document')),
                ('course', models.CharField(max_length=120, verbose_name='Course')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
            bases=('base.user',),
            managers=[
                ('objects', apps.base.managers.UserManager()),
            ],
        ),
    ]
